### PR TITLE
Upgrade to Swift 3 compatibility

### PR DESCRIPTION
**Pull request by chrismanderson**
Took a stab at running the Xcode Swift 3 migration for #83 ; everything seemed to carry over quite well. Test suite passes, and everything looks good in the sample project as well.

### CODE REVIEW

**Comment by eliperkins** [comment]
Awesome! This looks great. My only concern is merging this right into master, as opposed to maintaining a `swift-3` branch until Xcode 8 becomes GM. Merging in to master now would mean that no features will be added to Static before September. While we don't anticipate any large changes in Static, I'd like to keep the possibility open.

What do y'all think? @soffes @hyperspacemark

**Comment by soffes** [comment]
I made a Swift 3 branch myself :)

I think we should hold off until the GM. Making any changes in master will be really hard to port over to Swift 3 without just redoing it. I think if we started maintaining it now, we'd have a good chance of missing something that got added to master. I think I converted it in less than an hour when I did mine. (Also found a compiler bug while I was at it, so that was fun.)

Thanks for your work on this @chrismanderson, but I think we should hold off until the GM.

**Comment by chrismanderson** [comment]
Sounds good to me! I assumed you all wouldn't want to merge it in right away. I went to give it ago myself to work on Swift 3 compatibility in my main app and was surprised to see how fast the transition took. 

I'm happy to either 1) reopen the PR onto a swift-3 branch or 2) close entirely and let you all handle. Either works for me!

**Comment by soffes** [comment]
Let's close for now and revisit when the GM comes. Thanks again @chrismanderson :)

**Comment by chrismanderson** [comment]
Sounds good! 

And as a follow up, thanks for this repo in the first place! Every iOS developer seems to have their own method for static table views, and your approach is 👍 .

**Pull request closed without merging**
