### PR TITLE
Add option to disable automatically deselecting rows on selection

### PR DESCRIPTION
**Pull request by soffes**
Added this and turned it on to fix flashes when navigating. This doesn't change the current behavior. Just gives you an option to turn it off.

### CODE REVIEW

**Comment by soffes** [comment]
I think there's a case to make this `false` by default since `clearsSelectionOnViewWillAppear` is `true` by default. We revisit that when we make breaking changes though.

**Comment by hyperspacemark** [comment]
Cool this looks good to me as a fix for #65.

**Comment by aashishdhawan** [comment]
@soffes  @hyperspacemark Is this going to create a problem when user tries to do this   `tableView.allowsMultipleSelection = true`?

**Comment by hyperspacemark** [comment]
@aashishdhawan This diff doesn't change the current behavior, just adds a new option to control automatic deselections.

**Comment by soffes** [comment]
Thanks @hyperspacemark :heart:

**Pull request merged**
