### PR TITLE
Add in a row height property to customize row height of cells

### PR DESCRIPTION
**Pull request by jhaddadnia**

### CODE REVIEW

**Comment by eliperkins** [comment]
Thanks for the PR, @jhaddadnia!

Ah, this good ol' property again. Any reason we don't want take the approach outlined in https://github.com/venmo/Static/pull/60? `height` has been added and removed several times from the API now.

**Comment by jhaddadnia** [comment]
@eliperkins in this use case the tableView/Controller itself has been abstracted away from where the rows are being declared. So I'd like to be able to specify a height on a specific row/rows rather than subclassing the tableViewController and create a new cell class for every height requirement.
In regards to the row being agnostic of its presentation, sending a height seems analogous to sending in a title string. We don't send it the label or view itself, just a config string/float which is used to build the cell later.

**Comment by jhaddadnia** [comment]
I've been convinced 🙏  
...but no promises that I won't make the same pr in a couple months 😉

**Comment by eliperkins** [comment]
Haha awesome.

If there's anything we can make more clear in the docs or examples, I'd love to get that in there to convince Future Us™ too!

**Pull request closed without merging**
