### PR TITLE
Swift 4.2 / Xcode 10 Compatibility

### PR DESCRIPTION
**Pull request by cocoahero**

### CODE REVIEW

**Comment by dmiluski** [comment]
Thanks for the PR @cocoahero , I keep thinking CI was set up to validate this repo but wasn't seeing it here in the merge status. Was thinking we may need to update travis sdk? Will check after work.

**Comment by cocoahero** [comment]
You are correct that the `osx_image` will have to be updated to get TravisCI to work correctly. The new value should be `xcode10`. I can add this to the PR if you would like.

**Comment by cocoahero** [comment]
@dmiluski @eliperkins is there anything I can do to help get this PR finalized?

**Comment by dmiluski** [comment]
Looks good @cocoahero , I'll get this merged/released today

**Comment by dmiluski** [comment]
oops, merged and looks like there's a build break. Will fix shortly, and get CI wired back up to this repo for PR validation.

**Pull request merged**
