### PR TITLE
Allow replacing the data source in TableViewController

### PR DESCRIPTION
**Pull request by soffes**
Tested this in the demo app and it all works as expected.

Built this to make subclassing a bit easier. I'm working on a thing that has a segmented control at the top. Changing the segment changes the data in the table view. This change makes implementing this really easy.

### CODE REVIEW

**Comment by hyperspacemark** [comment]
I dig it.

**Comment by soffes** [comment]
Thinking about this more, I really should just be changing `dataSource.sections` instead of the whole data source. That said, this doesn't hurt anything. If someone subclassed for whatever reason (which maybe we should add `final` to `DataSource` since it would be tough to add any real value by subclassing without messing up stuff. That said, no sense in letting someone try I suppose) it would be easy to swap it. I think it's fine, but my example isn't a good one.

**Comment by soffes** [comment]
Actually, given #39, this is great. In my segmented control, one of my segments has an index and one doesn't. Swapping the whole data source is super handy.

**Comment by soffes** [comment]
Closing since this is in #39 now.

**Pull request closed without merging**
